baseURL: https://alanoakes.github.io/
languageCode: en-us
defaultContentLanguage: en
title: Log Blog
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tags: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Have a question? Feel free to contact me or post an issue on my github.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed by [Github Pages](https://pages.github.com/).
  dateFormat: Jan 02, 2006
  katex: true
  hideHeaderLinks: true
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Log Blog
  customCss:
    # - css/dark.min.css
    - css/github-dark.min.css
  customJs:
    - js/highlight.min.js
    # - js/custom_02.js
  utterances:
    repo: alanoakes/alanoakes.github.io
    issueTerm: title
    theme: github-light

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: Projects
      url: /projects/
      weight: 4
    - name: About
      url: /about/
      weight: 5
    - name: RSS
      url: /index.xml
      weight: 6

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: dark
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
